services:
  db_postgres:
    image: postgres:16  # Usa la versione 16 di Postgres
    container_name: BugBoard26_DB
    restart: always # Se il container crasha, si riavvia da solo
    ports:
      - "${DB_PORT}:5432" # Mappa la porta del PC (sinistra) su quella del container (destra)
    environment:
      POSTGRES_USER: ${DB_USER}       # Utente del DB
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Password del DB
      POSTGRES_DB: ${DB_NAME}    # Nome del DB che verrà creato vuoto
    volumes:
      - postgres_data:/var/lib/postgresql/data # Salva i dati sul tuo disco

  pgadmin:
    image: dpage/pgadmin4
    container_name: BugBoard26_PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}  # Email per accedere a pgAdmin
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}  # Password per accedere a pgAdmin
    ports:
      - "5050:80"  # pgAdmin sarà disponibile sulla porta 5050
    depends_on:
      - db_postgres


volumes:
  postgres_data: # Definisce il volume per non perdere i dati se spegni Docker